name: elaichi
description: Campus Guide for NIT Rourkela

version: 0.0.1+1

environment:
  sdk: '>=2.7.0 <3.0.0'

# dependency_overrides:
# analyzer: "0.39.14"

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^0.9.2

  # State management
  stacked: ^1.6.0

  # Navigation
  auto_route: ^0.6.6
  stacked_services: ^0.5.0

  # Inversion of control(dependency injection)
  get_it: ^5.0.3
  injectable: ^1.0.5
  dartz: ^0.9.1

  # Themes
  stacked_themes: ^0.2.2+2

  # Localisation
  easy_localization: ^2.3.3

  # Local database
  hive: ^1.4.3
  hive_flutter: ^0.3.1

  # GraphQL client library
  graphql: ^4.0.0-beta.6
  
  # Authentications
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  mockito: ^4.1.1

  build_runner: ^1.10.3
  auto_route_generator: ^0.6.6
  injectable_generator: ^1.0.6

  # Local database
  hive_generator: ^0.7.1

  # graphql generator
  gql_code_gen: ^0.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
